<?

/*********************************************************

This is an Webfrontend for the Database
generated by Quakealyzer

You're free to write your own, or modify it to your own needs.

For more information take a look into info.txt

*********************************************************/

session_start();

require_once ('conf.php');
require_once ('database.php');

$conf = new Conf();
$path = new Path();
$msg = new Message();
$translate = new Translator();
$db = new Database($conf->db_host, $conf->db_name, $conf->db_user, $conf->db_password);

require_once ('lib.php');
$view = new View();
$package = new Package();

//Login mechanics
if ( $conf->use_login) {
    if ( ! check_login()) {
        exit();
    }
}


$game_list = $db->get_game_list();
$user_list = $db->get_user_list();
$map_list = $db->get_map_list();
$item_list = $db->get_item_list();
$used_weapons_list = $db->get_kill_weapon_list();
$game_type_list = $db->get_game_type_list();
$end_cause_list = $db->get_end_cause_list();
$game_mod_list = $db->get_mod_list();
$model_list = $db->get_model_list();
$hmodel_list = $db->get_hmodel_list();

check_property($path, 'exist');

//extract images from new packages (only on set intervall)
if ( ($conf->auto_discovery_new_packages) &&
    (time() > ($db->get_config('last_sync') + $conf->sync_intervall)) ) {
    $package->check_packages($db);
    $db->set_config('last_sync', time() );
}
?>

<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css" href="style.css" />
</head>
<title>
<?=$msg->title_text?>
</title>
<body>

<div class="div_sidebar">
<?
include('sidebar.php');
?>
</div>

<div class="div_content">
<?
include('content.php');
?>
</div>

</body>
</html>
